# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string
    secrets:
      IONOS_API_KEY:
        required: true

env:
  DEPLOYMENT_FOLDER: dist

jobs:
# Please do not rename this job
  build-project:
    name: build primis3d
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: v22.x
          cache: npm

      - name: Build Node assets
        env:
          CI: true
          SITE_URL: ${{ inputs.site-url }}
        run: |
          npm ci
          npm run build

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@184a369b679287c06ff3d4392cf57bf0fd32656e # v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 42582a72-3cd9-4310-aa1c-20407dbe41d1
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/primis3d/config.yaml
          action: upload
